
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/zoning
    password: marcus254
    username: postgres


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    enabled: true
    change-log: db/changelog/changelog-master.xml
server:
  port: 8181
